name: project_camel
description: "An App for excessive funnel-drinking"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^17.0.0

  # Icons
  flutter_svg: ^2.0.9

  # State Management
  flutter_riverpod: ^3.0.3

  # Bluetooth
  flutter_blue_plus: ^2.1.0

  # Permissions
  permission_handler: ^12.0.1

  #SQLite
  sqflite: ^2.4.2

  path: ^1.8.3

  uuid: ^4.5.2

  intl: ^0.20.2

  equatable: ^2.0.5

  jwt_decoder: ^2.0.1

  #flutter_jwt_auth: ^1.0.0

  flutter_secure_storage: ^10.0.0

  dio: ^5.7.0

  flutter_bloc: ^9.1.1

  url_launcher: ^6.3.0

  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/